### ISSUE TITLE
Not working on generated models

### ISSUE THREAD

**Issue by moechakucha** [Prismwork/flexible-arms#1]
~~i wanted to add steve the vindicator~~

**Comment by ianaduarte** [comment]
heya! I wound up figuring how to fix this, you need to modify the return value of ItemModelGenerator's `create` method in a similar way as to what you did in JsonUnbakedModel's `bake` method. I would submit a PR or something, but I actually did this in my own mod library thingy.

**Comment by moechakucha** [comment]
that would be helpful, thanks!
